apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: ai-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: ai-gateway:v9
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: api-gateway-config
            - secretRef:
                name: llm-api-keys
          env:
            - name: APP_REDIS_HOST
              value: "redis"
          volumeMounts:
            - name: settings-volume
              mountPath: /app/config
              readOnly: true
      volumes:
        - name: settings-volume
          configMap:
            name: gateway-settings