apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - redis-deployment.yaml
  - redis-service.yaml
  - api-gateway-config.yaml
  - gateway-settings.yaml
  - api-gateway-deployment.yaml
  - api-gateway-service.yaml
  - ollama-pvc.yaml
  - ollama-deployment.yaml
  - ollama-service.yaml
  - qdrant-statefulset.yaml
  - qdrant-service.yaml